### PR TITLE
[*] Updated Stellar SDK to 1.0.0-alpha0

### PR DESCRIPTION
**Pull request by overcat**
This PR upgrades the Stellar SDK to the latest version. I have no experience in developing Android apps at all, so I only made minimal changes. Please let me know if there are any issues.

### CODE REVIEW

**Comment by silent-grass** [comment]
@overcat 
Thank you so much for your work!

I already have local branch with necessary changes for 1.0.0-alpha0 release (also `Assets` rework and `TrustLineEntryFlag` mapper). I have compared one with yours and make necessary changes.

**Comment by overcat** [comment]
Hi @silent-grass. Cool! could you please submit your PR to this repository? If possible, I would like to use it as a reference for other users. Thank you.

> @overcat Thank you so much for your work!
> 
> I already have local branch with necessary changes for 1.0.0-alpha0 release (also `Assets` rework and `TrustLineEntryFlag` mapper). I have compared one with yours and make necessary changes.

**Comment by silent-grass** [comment]
@overcat I apologize for the late response.
[PR](https://github.com/Lobstrco/Vault-Android/pull/6) with Stellar SDK 1.0.0-beta0 support.

**Comment by overcat** [comment]
> @overcat I apologize for the late response. [PR](https://github.com/Lobstrco/Vault-Android/pull/6) with Stellar SDK 1.0.0-beta0 support.

Thanks! Very cool!

**Pull request closed without merging**
